# encoding: utf-8

class SeedInfluenceZones < ActiveRecord::Migration
  def up
    InfluenceZone.create( zone_name: 'Neuquen', tag_name: 'ZI-AMS-AR-PAT (Patagonia)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Santa Cruz', tag_name: 'ZI-AMS-AR-PAT (Patagonia)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Chubut', tag_name: 'ZI-AMS-AR-PAT (Patagonia)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Tierra del Fuego', tag_name: 'ZI-AMS-AR-PAT (Patagonia)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Capital Federal', tag_name: 'ZI-AMS-AR-BUE (Buenos Aires)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Buenos Aires', tag_name: 'ZI-AMS-AR-BUE (Buenos Aires)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Córdoba', tag_name: 'ZI-AMS-AR-CTR (Centro)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'La Pampa', tag_name: 'ZI-AMS-AR-CTR (Centro)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Santa Fé', tag_name: 'ZI-AMS-AR-CTR (Centro)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Corrientes', tag_name: 'ZI-AMS-AR-LIT (Litoral)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Misiones', tag_name: 'ZI-AMS-AR-LIT (Litoral)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Entre Rios', tag_name: 'ZI-AMS-AR-LIT (Litoral)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Chaco', tag_name: 'ZI-AMS-AR-LIT (Litoral)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Formosa', tag_name: 'ZI-AMS-AR-LIT (Litoral)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Santiago del Estero', tag_name: 'ZI-AMS-AR-NOA (Noroeste)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Tucumán', tag_name: 'ZI-AMS-AR-NOA (Noroeste)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'La Rioja', tag_name: 'ZI-AMS-AR-NOA (Noroeste)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Salta', tag_name: 'ZI-AMS-AR-NOA (Noroeste)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Jujuy', tag_name: 'ZI-AMS-AR-NOA (Noroeste)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Catamarca', tag_name: 'ZI-AMS-AR-NOA (Noroeste)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'Mendoza', tag_name: 'ZI-AMS-AR-CUY (Cuyo)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'San Juan', tag_name: 'ZI-AMS-AR-CUY (Cuyo)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: 'San Luis', tag_name: 'ZI-AMS-AR-CUY (Cuyo)', country_id: Country.find_by_iso_code( 'AR' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AUS (Australia)', country_id: Country.find_by_iso_code( 'AU' ).id )
    InfluenceZone.create( zone_name: 'Cochabamba', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'La Paz', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Santa Cruz', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Tarija', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Pando', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Potosí', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Oruro', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Chuquisaca', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Beni', tag_name: 'ZI-AMS-BO (Bolivia)', country_id: Country.find_by_iso_code( 'BO' ).id )
    InfluenceZone.create( zone_name: 'Acre', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Alagoas', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Rio de Janeiro', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Sao Paulo', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Amapá', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Amazonas', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Bahia', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Ceará', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Espírito Santo', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Goiás', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Mato Grosso', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Mato Grosso do Sul', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Minas Gerais', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Pará', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Paraíba', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Paraná', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Pernambuco', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Piauí', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Rio de Janeiro', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Rio Grande do Norte', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Rio Grande do Sul', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Rondônia', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Roraima', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Santa Catarina', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'São Paulo', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Sergipe', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: 'Tocantins', tag_name: 'ZI-AMS-BR (Brasil)', country_id: Country.find_by_iso_code( 'BR' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMN-CA (Canada)', country_id: Country.find_by_iso_code( 'CA' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMS-CL (Chile)', country_id: Country.find_by_iso_code( 'CL' ).id )
    InfluenceZone.create( zone_name: 'Armenia', tag_name: 'ZI-AMS-CO-EJE (Eje cafetero)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Pereira', tag_name: 'ZI-AMS-CO-EJE (Eje cafetero)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Manizales', tag_name: 'ZI-AMS-CO-EJE (Eje cafetero)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Barranquilla', tag_name: 'ZI-AMS-CO-CAR (Caribe)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Cartagena', tag_name: 'ZI-AMS-CO-CAR (Caribe)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Santa Marta', tag_name: 'ZI-AMS-CO-CAR (Caribe)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Monteria', tag_name: 'ZI-AMS-CO-CAR (Caribe)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Valledupar', tag_name: 'ZI-AMS-CO-CAR (Caribe)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Sincelejo', tag_name: 'ZI-AMS-CO-CAR (Caribe)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Bogota', tag_name: 'ZI-AMS-CO-BOG (Bogota)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Tunja', tag_name: 'ZI-AMS-CO-BOG (Bogota)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Villavicencio', tag_name: 'ZI-AMS-CO-BOG (Bogota)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Neiva', tag_name: 'ZI-AMS-CO-BOG (Bogota)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Ibagué', tag_name: 'ZI-AMS-CO-BOG (Bogota)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Bucaramanga', tag_name: 'ZI-AMS-CO-SAN (Santander)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Cúcuta', tag_name: 'ZI-AMS-CO-SAN (Santander)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Cali', tag_name: 'ZI-AMS-CO-PAC (Pacífico)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Popayan', tag_name: 'ZI-AMS-CO-PAC (Pacífico)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Pasto', tag_name: 'ZI-AMS-CO-PAC (Pacífico)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Quibdó', tag_name: 'ZI-AMS-CO-PAC (Pacífico)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'Medellin', tag_name: 'ZI-AMS-CO-MDE (Medellín)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: 'N/A', tag_name: 'ZI-AMS-CO-BOG (Bogota)', country_id: Country.find_by_iso_code( 'CO' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMC (America Central y Caribe)', country_id: Country.find_by_iso_code( 'CU' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMC (America Central y Caribe)', country_id: Country.find_by_iso_code( 'GT' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMC (America Central y Caribe)', country_id: Country.find_by_iso_code( 'HN' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMS-EC (Ecuador)', country_id: Country.find_by_iso_code( 'EC' ).id )
    InfluenceZone.create( zone_name: 'Andalucía', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Aragón', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Principado de Asturias', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Islas Baleares', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Canarias', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Cantabria', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Castila-La Mancha', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Castilla y León', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Cataluña', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Comunidad Valenciana', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Extremadura', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Galicia', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'La Rioja', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Comunidad de Madrid', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Comunidad Foral de Navarra', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'País Vasco', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Región de Murcia', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Ceuta', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: 'Melilla', tag_name: 'ZI-EUR-ES (España)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-ASI (Asia)', country_id: Country.find_by_iso_code( 'ES' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMN-MX (Mexico)', country_id: Country.find_by_iso_code( 'MX' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMC (America Central y Caribe)', country_id: Country.find_by_iso_code( 'PA' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMS-PY (Paraguay)', country_id: Country.find_by_iso_code( 'PY' ).id )
    InfluenceZone.create( zone_name: 'Amazonas', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Áncash', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Apurímac', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Arequipa', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Ayacucho', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Cajamarca', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Callao', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Cusco', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Huancavelica', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Huánuco', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Ica', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Junín', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'La Libertad', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Lambayeque', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Lima', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Loreto', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Madre de Dios', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Moquegua', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Pasco', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Piura', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Puno', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'San Martín', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Tacna', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Tumbes', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: 'Ucayali', tag_name: 'ZI-AMS-PE (Peru)', country_id: Country.find_by_iso_code( 'PE' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMC (America Central y Caribe)', country_id: Country.find_by_iso_code( 'DO' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMS-UY (Uruguay)', country_id: Country.find_by_iso_code( 'UY' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMN-US (EEUU)', country_id: Country.find_by_iso_code( 'US' ).id )
    InfluenceZone.create( zone_name: '', tag_name: 'ZI-AMS-VE (Venezuela)', country_id: Country.find_by_iso_code( 'VE' ).id )
    
    br = Country.find_by_iso_code( 'BR' )
    br.name = "Brasil"
    br.save!
    
    es = Country.find_by_iso_code( 'ES' )
    es.name = "España"
    es.save!
    
    dom = Country.find_by_iso_code( 'DO' )
    dom.name = "República Dominicana"
    dom.save!
    
    us = Country.find_by_iso_code( 'US' )
    us.name = "Estados Unidos"
    us.save!
    
    ve = Country.find_by_iso_code( 'VE' )
    ve.name = "Venezuela"
    ve.save!    
  end

  def down
    InfluenceZone.delete_all
  end
end
